name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Greet
      run: echo "Hello ${{ github.event.inputs.name }}!"

  print-date:
    runs-on: ubuntu-latest
    steps:
    - name: Print current date
      run: date
